echo "Este script ha recibido $# argumentos"
echo "El nombre del script es: $0"
echo "Mi primer argumento es: $1"
echo "Mi segundo argumento es: $2"
echo "Mi tercer argumento es: $3"
echo "La lista de todos mis argumentos: $*"
